"""Constants holds the constants used in graphdriver.

    Always sort ascending when adding new constants.
"""
ALL = "all"
CANCER = "cancer"
CANDIDATES = "candidates"
CGO = "cgo"
CONFIDENCE = "confidence"
DRIVERS_CANCER = "drivers_cancer"
DRIVERS_OTHER = "drivers_other"
FPKM = "fpkm"
GENES = "genes"
HUGO = "hugo"
NCG = "ncg"
NORMAL = "normal"
OUTS = "outs"
PANCANCER = "pancancer"
PASSENGERS = "passengers"
PPI = "ppi"
SYM_SOURCE = "source_symbol"
SYM_TARGET = "target_symbol"
SYMBOL = "symbol"
TCGA_GENES = "tcga_genes"
TCGA_MUTATIONS = "tcga_mutations"
TEST = "test"
TPM = "tpm"
TRAIN = "train"
TUMOR = "tumor"
VAL = "val"
